// frontend/src/routes/form/Navigation.svelte
<script>
	const { currentStep, totalSteps, onPrevious, onNext } = $props();
	const isPreviewStep = $derived(currentStep === totalSteps);
</script>

<div class="flex justify-between border-t border-gray-200 pt-6">
	{#if currentStep > 1}
		<button
			type="button"
			onclick={onPrevious}
			class="rounded-lg border border-gray-300 bg-white px-6 py-3 text-base font-medium text-gray-700 transition-colors duration-200 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
		>
			Previous
		</button>
	{/if}

	<div class="ml-auto">
		{#if isPreviewStep}
			<button
				type="submit"
				class="rounded-lg bg-green-400 px-6 py-3 font-medium text-white transition-colors duration-200 hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
			>
				Submit
			</button>
		{:else}
			<button
				type="button"
				onclick={onNext}
				class="rounded-lg bg-blue-600 px-6 py-3 font-medium text-white transition-colors duration-200 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
			>
				Next
			</button>
		{/if}
	</div>
</div>

// frontend/src/components/form/navigation.tsx

interface FormNavigationProps {
	currentStep: number;
	totalSteps: number;
	onPrevious: () => void;
	onNext: () => void;
}

export function FormNavigation({ currentStep, totalSteps, onPrevious, onNext }: FormNavigationProps) {
	const isPreviewStep = currentStep === totalSteps;

	return (
		<div className="flex justify-between pt-6 border-t border-gray-200">
			{currentStep > 1 && (
				<button
					type="button"
					onClick={onPrevious}
					className="px-6 py-3 border border-gray-300 rounded-lg text-base font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors duration-200"
				>
					Previous
				</button>
			)}
			<div className="ml-auto">
				{isPreviewStep ? (
					<button
						type="submit"
						className="px-6 py-3 bg-green-600 text-white font-medium rounded-lg hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 transition-colors duration-200"
					>
						Submit
					</button>
				) : (
					<button
						type="button"
						onClick={onNext}
						className="px-6 py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors duration-200"
					>
						Next
					</button>
				)}
			</div>
		</div>
	);
}
