// frontend/src/components/form/index.tsx
import type { JobData } from '../../types/job';
import { CompensationSection } from './sections/compensation';
import { CompanySection } from './sections/company';
import { ProgramSection } from './sections/program';
import { PreviewSection } from './sections/preview';
import { FormProgress } from './progress';
import { FormNavigation } from './navigation';
import { useFormSteps } from '../../hooks/useFormSteps';
import { useFormState } from '../../hooks/useFormStates';

interface JobFormProps {
	onSubmit: (data: JobData) => void;
}

const initialFormData: JobData = {
	companyName: '',
	position: '',
	majors: [],
	minors: [],
	salary: 50,
	salaryNA: false,
	location: '',
	workHours: 40,
	coopYear: '1st',
	coopCycle: 'spring/summer',
	compensations: [],
	level: 'undergraduate',
	source: 'SCDC'
};

const stepTitles = ['Company', 'Compensation', 'Program', 'Preview'];

export function JobForm({ onSubmit }: JobFormProps) {
	const {
		formData,
		updateFormData,
		resetFormData
	} = useFormState(initialFormData);

	const {
		currentStep,
		totalSteps,
		errors,
		goToStep,
		goToNextStep,
		goToPreviousStep,
		clearStepState
	} = useFormSteps(4);

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault();
	};

	const handleFinalSubmit = () => {
		onSubmit(formData);
		resetFormData();
		clearStepState();
		goToStep(1, initialFormData);
	};

	const renderStepContent = () => {
		switch (currentStep) {
			case 1:
				return <CompanySection formData={formData} onChange={updateFormData} />;
			case 2:
				return <CompensationSection formData={formData} onChange={updateFormData} />;
			case 3:
				return <ProgramSection formData={formData} onChange={updateFormData} />;
			case 4:
				return (
					<PreviewSection
						formData={formData}
						onSubmit={handleFinalSubmit}
						onBack={() => goToPreviousStep()}
					/>
				);
			default:
				return null;
		}
	};

	return (
		<form onSubmit={handleSubmit} className="space-y-8 bg-white p-8 rounded-xl shadow-lg max-w-6xl mx-auto">
			<FormProgress
				currentStep={currentStep}
				totalSteps={totalSteps}
				stepTitles={stepTitles}
				onStepClick={(step) => goToStep(step, formData)}
				errors={errors}
			/>
			{renderStepContent()}
			{currentStep < totalSteps && (
				<FormNavigation
					currentStep={currentStep}
					totalSteps={totalSteps}
					onPrevious={goToPreviousStep}
					onNext={() => goToNextStep(formData)}
				/>
			)}
		</form>
	);
}

// src/routes/form/+page.svelte
<script>
	import FormNavigation from './Navigation.svelte';
	import FormProgress from './Progress.svelte';
	import CompanySection from './sections/Company.section.svelte';
	import ProgramSection from './sections/Program.section.svelte';
	import CompensationSection from './sections/Compensation.section.svelte';

	let formData = $state({
		companyName: '',
		position: '',
		majors: [],
		minors: [],
		location: '',
		workHours: 0,
		coopYear: '',
		coopCycle: '',
		compensations: [],
		level: '',
		source: '',
		offerStatus: '',
		decision: '',
		decisionReason: '',
		otherNotes: ''
	});

	const stepTitles = [
		{ label: 'Company', component: CompanySection },
		{ label: 'Program', component: ProgramSection },
		{ label: 'Compensation', component: CompensationSection }
	];
	let currentStep = $state(1);
	const errors = $state({});

	const totalSteps = stepTitles.length;

	function handleSubmit(event) {
		event.preventDefault();
	}

	function goToStep(step) {
		currentStep = step;
	}

	function goToPreviousStep() {
		if (currentStep > 1) {
			currentStep--;
		}
	}

	function goToNextStep() {
		if (currentStep < totalSteps) {
			currentStep++;
		}
	}
</script>

<div class="px-4 py-12 sm:px-6 lg:px-8">
	<form onsubmit={handleSubmit} class="mx-36 max-w-6xl space-y-8 rounded-xl bg-white p-8 shadow-lg">
		<h2 class="mb-6 text-2xl font-bold text-gray-900">Anonymous Salary Form</h2>

		<FormProgress
			{currentStep}
			stepTitles={stepTitles.map((item) => item.label)}
			onStepClick={goToStep}
			{errors}
		/>

		{#each stepTitles as item, idx}
			{#if idx + 1 == currentStep}
				<item.component bind:formData />
			{/if}
		{/each}

		{#if currentStep < totalSteps}
			<FormNavigation
				{currentStep}
				{totalSteps}
				onPrevious={goToPreviousStep}
				onNext={goToNextStep}
			/>
		{/if}
	</form>
</div>
