// src/lib/client/components/AutoComplete.svelte
<script>
	import { onMount, onDestroy } from 'svelte';

	const {
		options = [],
		value = '',
		onChange = (val) => {},
		onAddOption = (val) => {},
		label = '',
		fetchOptions,
		searchOptions
	} = $props();

	let isOpen = $state(false);
	let inputValue = $state(value);
	let filteredOptions = $state([]);
	let loading = $state(false);
	let wrapperRef;
	let inputRef;
	let inputId = `autocomplete-${Math.random().toString(36).substr(2, 9)}`;

	$effect(() => {
		inputValue = value;
	});

	$effect(() => {
		if (searchOptions) {
			filteredOptions = searchOptions(options, inputValue);
		} else {
			filteredOptions = options.filter((option) =>
				option.toLowerCase().includes(inputValue.toLowerCase())
			);
		}
	});

	let handleClickOutside;

	onMount(() => {
		handleClickOutside = (event) => {
			if (wrapperRef && !wrapperRef.contains(event.target)) {
				isOpen = false;
			}
		};

		document.addEventListener('mousedown', handleClickOutside);
	});

	onDestroy(() => {
		if (handleClickOutside) {
			document.removeEventListener('mousedown', handleClickOutside);
		}
	});

	async function handleInputChange(e) {
		inputValue = e.target.value;
		onChange(inputValue);
		isOpen = true;

		if (fetchOptions) {
			try {
				loading = true;
				const newOptions = await fetchOptions(inputValue);
				filteredOptions = newOptions;
			} catch (error) {
				console.error('Error fetching options:', error);
				filteredOptions = [];
			} finally {
				loading = false;
			}
		}
	}

	function handleOptionClick(option) {
		inputValue = option;
		onChange(option);
		isOpen = false;
	}

	function handleOptionKeyDown(e, option) {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			handleOptionClick(option);
		}
	}

	function handleAddOption() {
		if (inputValue.trim()) {
			onAddOption(inputValue.trim());
			handleOptionClick(inputValue.trim());
		}
	}

	function handleAddOptionKeyDown(e) {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			handleAddOption();
		}
	}
</script>

<div class="relative w-full" bind:this={wrapperRef}>
	<span for={inputId} class="mb-2 font-medium text-gray-700">
		{label}
	</span>
	<input
		id={inputId}
		bind:this={inputRef}
		type="text"
		value={inputValue}
		oninput={handleInputChange}
		onfocus={() => (isOpen = true)}
		class="w-full rounded-md border border-gray-300 px-4 py-2 focus:border-transparent focus:ring-2 focus:ring-blue-500"
		role="combobox"
		aria-expanded={isOpen}
		aria-controls="autocomplete-options"
		aria-autocomplete="list"
	/>
	{#if isOpen}
		<div
			id="autocomplete-options"
			class="absolute z-10 mt-1 w-full rounded-md border border-gray-300 bg-white shadow-lg"
			role="listbox"
		>
			{#if loading}
				<div class="flex justify-center p-2">
					<div
						class="h-5 w-5 animate-spin rounded-full border-2 border-blue-500 border-t-transparent"
					></div>
				</div>
			{:else if filteredOptions.length > 0}
				{#each filteredOptions as option}
					<button
						type="button"
						onclick={() => handleOptionClick(option)}
						onkeydown={(e) => handleOptionKeyDown(e, option)}
						class="w-full cursor-pointer px-4 py-2 text-left hover:bg-gray-100"
						role="option"
						aria-selected={inputValue === option}
					>
						{option}
					</button>
				{/each}
			{:else}
				<button
					type="button"
					onclick={handleAddOption}
					onkeydown={handleAddOptionKeyDown}
					class="w-full cursor-pointer px-4 py-2 text-left text-blue-600 hover:bg-gray-100"
				>
					Add "{inputValue}"
				</button>
			{/if}
		</div>
	{/if}
</div>

// frontend/src/components/ui/autocomplete.tsx
import React, { useState, useRef, useEffect } from 'react';
import { Loader2, Plus, Search } from 'lucide-react';

interface AutocompleteInputProps {
  config: { title: string, icon: any, type: any, allowSuggestions: boolean };
  value: string;
  onChange: (value: string) => void;
  options: string[];
  onSuggestion?: (value: string) => void;
  loading?: boolean;
}

export function AutocompleteInput({
  config,
  value,
  onChange,
  options,
  onSuggestion,
  loading = false
}: AutocompleteInputProps) {
  const [search, setSearch] = useState('');
  const [showOptions, setShowOptions] = useState(false);
  const wrapperRef = useRef<HTMLDivElement>(null);
  const Icon = config.icon;

  const filteredOptions = options.filter(option =>
    option.toLowerCase().includes((search || '').toLowerCase())
  );

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (wrapperRef.current && !wrapperRef.current.contains(event.target as Node)) {
        setShowOptions(false);
        if (!value) {
          setSearch('');
        }
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [value]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value;
    setSearch(newValue);
    setShowOptions(true);

    if (!newValue) {
      onChange('');
    }
  };

  const handleOptionSelect = (option: string) => {
    onChange(option);
    setSearch('');
    setShowOptions(false);
  };

  const handleSuggestion = () => {
    if (config.allowSuggestions && onSuggestion && search) {
      onSuggestion(search);
      setSearch('');
      setShowOptions(false);
    }
  };

  const displayValue = search || value;

  return (
    <div ref={wrapperRef} className="space-y-2">
      <label className="text-sm font-medium text-gray-700 flex items-center gap-2">
        {Icon && <Icon className="w-4 h-4 text-gray-500" />}
        {config.title}
      </label>
      <div className="relative">
        <input
          type="text"
          required
          placeholder={loading ? 'Loading...' : `Select ${config.type}...`}
          className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors duration-200"
          value={displayValue}
          onChange={handleInputChange}
          onFocus={() => setShowOptions(true)}
          disabled={loading}
        />
        {loading ? (
          <Loader2 className="w-5 h-5 absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 animate-spin" />
        ) : config.allowSuggestions && search && !filteredOptions.length ? (
          <button
            type="button"
            onClick={handleSuggestion}
            className="absolute right-3 top-1/2 -translate-y-1/2 text-blue-600 hover:text-blue-700"
          >
            <Plus className="w-5 h-5" />
          </button>
        ) : (
          <Search className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
        )}
        {showOptions && !loading && filteredOptions.length > 0 && (
          <div className="absolute z-10 w-full mt-1 bg-white border border-gray-300 rounded-lg shadow-lg max-h-60 overflow-y-auto">
            {filteredOptions.map((option) => (
              <div
                key={option}
                className="px-4 py-2 hover:bg-blue-50 cursor-pointer transition-colors duration-150"
                onClick={() => handleOptionSelect(option)}
              >
                {option}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
