// src/lib/client/components/MultiSelect.svelte
<script>
	import { onMount, onDestroy } from 'svelte';

	// Props using Svelte's export syntax
	const {
		options = [],
		values = [],
		onChange = (vals) => {},
		onAddOption = (val) => {},
		label = ''
	} = $props();

	let isOpen = $state(false);
	let inputValue = $state('');
	let filteredOptions = $state([]);
	let inputRef;
	let wrapperRef;

	const inputId = `multiselect-${Math.random().toString(36).substr(2, 9)}`;

	$effect(() => {
		filteredOptions = options.filter(
			(option) =>
				option.toLowerCase().includes(inputValue.toLowerCase()) && !values.includes(option)
		);
	});

	onMount(() => {
		const handleClickOutside = (event) => {
			if (wrapperRef && !wrapperRef.contains(event.target)) {
				isOpen = false;
			}
		};

		document.addEventListener('mousedown', handleClickOutside);

		return () => {
			document.removeEventListener('mousedown', handleClickOutside);
		};
	});

	function handleInputChange(e) {
		inputValue = e.target.value;
		isOpen = true;
	}

	function handleOptionClick(option) {
		onChange([...values, option]);
		inputValue = '';
		if (inputRef) {
			inputRef.focus();
		}
	}

	function handleOptionKeyDown(e, option) {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			handleOptionClick(option);
		}
	}

	function handleRemoveValue(valueToRemove) {
		onChange(values.filter((value) => value !== valueToRemove));
	}

	function handleAddOption() {
		if (inputValue && !options.includes(inputValue)) {
			onAddOption(inputValue);
			onChange([...values, inputValue]);
			inputValue = '';
		}
	}

	function handleAddOptionKeyDown(e) {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			handleAddOption();
		}
	}
</script>

<div class="relative w-full" bind:this={wrapperRef}>
	<span for={inputId} class="mb-1 block font-medium text-gray-700">
		{label}
	</span>
	<div
		class="min-h-[42px] rounded-md border border-gray-300 p-1 focus-within:border-transparent focus-within:ring-2 focus-within:ring-blue-500"
	>
		<div class="flex flex-wrap gap-1">
			{#each values as value}
				<span
					class="inline-flex items-center rounded-md border-transparent bg-blue-100 px-2 py-1 text-sm text-blue-800"
				>
					{value}
					<button
						type="button"
						onclick={() => handleRemoveValue(value)}
						class="ml-1 text-blue-600 hover:text-blue-800"
						aria-label={`Remove ${value}`}
					>
						×
					</button>
				</span>
			{/each}
			<input
				id={inputId}
				bind:this={inputRef}
				type="text"
				bind:value={inputValue}
				oninput={handleInputChange}
				onfocus={() => (isOpen = true)}
				class="min-w-[120px] flex-1 border-transparent p-1 outline-none"
				placeholder="Type to search..."
				aria-expanded={isOpen}
				aria-controls="multiselect-options"
				role="combobox"
			/>
		</div>
	</div>
	{#if isOpen && (inputValue || filteredOptions.length > 0)}
		<div
			id="multiselect-options"
			class="absolute z-10 mt-1 w-full rounded-md border border-transparent bg-white shadow-lg"
			role="listbox"
		>
			{#if filteredOptions.length > 0}
				{#each filteredOptions as option}
					<button
						type="button"
						onclick={() => handleOptionClick(option)}
						onkeydown={(e) => handleOptionKeyDown(e, option)}
						class="w-full cursor-pointer px-4 py-2 text-left hover:bg-gray-100"
						role="option"
						aria-selected="false"
					>
						{option}
					</button>
				{/each}
			{:else if inputValue}
				<button
					type="button"
					onclick={handleAddOption}
					onkeydown={handleAddOptionKeyDown}
					class="w-full cursor-pointer px-4 py-2 text-left text-blue-600 hover:bg-gray-100"
				>
					Add "{inputValue}"
				</button>
			{/if}
		</div>
	{/if}
</div>

// frontend/src/components/ui/multiselect.tsx
import React, { useState, useRef, useEffect } from 'react';
import { X, Plus } from 'lucide-react';

interface MultiSelectProps {
  label: string;
  icon: React.ReactNode;
  options: string[];
  values: string[];
  onChange: (values: string[]) => void;
  maxItems?: number;
  required?: boolean;
  placeholder?: string;
}

export function MultiSelect({
  label,
  icon,
  options,
  values,
  onChange,
  maxItems = 5,
  required = false,
  placeholder = 'Select...'
}: MultiSelectProps) {
  const [search, setSearch] = useState('');
  const [showOptions, setShowOptions] = useState(false);
  const wrapperRef = useRef<HTMLDivElement>(null);

  const filteredOptions = options.filter(
    option =>
      !values.includes(option) &&
      option.toLowerCase().includes(search.toLowerCase())
  );

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (wrapperRef.current && !wrapperRef.current.contains(event.target as Node)) {
        setShowOptions(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleAdd = (option: string) => {
    if (values.length < maxItems) {
      onChange([...values, option]);
      setSearch('');
      setShowOptions(false);
    }
  };

  const handleRemove = (option: string) => {
    onChange(values.filter(v => v !== option));
  };

  const canAddMore = values.length < maxItems;

  return (
    <div ref={wrapperRef} className="space-y-2">
      <label className="block text-sm font-medium text-gray-700">
        <div className="flex items-center gap-2">
          {icon}
          {label}
          {required && <span className="text-red-500">*</span>}
        </div>
      </label>

      {/* Selected Items */}
      <div className="flex flex-wrap gap-2 mb-2">
        {values.map((value) => (
          <span
            key={value}
            className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full bg-blue-100 text-blue-800 text-sm"
          >
            {value}
            <button
              type="button"
              onClick={() => handleRemove(value)}
              className="p-0.5 hover:bg-blue-200 rounded-full transition-colors duration-150"
            >
              <X className="w-3 h-3" />
            </button>
          </span>
        ))}
      </div>

      {/* Input Field */}
      {canAddMore && (
        <div className="relative">
          <div className="relative">
            <input
              type="text"
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                setShowOptions(true);
              }}
              onFocus={() => setShowOptions(true)}
              className="w-full px-4 py-2.5 rounded-lg border border-gray-300 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors duration-200"
              placeholder={placeholder}
            />
            <Plus className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
          </div>

          {/* Dropdown */}
          {showOptions && filteredOptions.length > 0 && (
            <div className="absolute z-10 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg max-h-60 overflow-y-auto">
              {filteredOptions.map((option) => (
                <button
                  key={option}
                  type="button"
                  className="w-full px-4 py-2 text-left hover:bg-blue-50 transition-colors duration-150"
                  onClick={() => handleAdd(option)}
                >
                  {option}
                </button>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Helper Text */}
      <p className="text-sm text-gray-500 flex items-center justify-between">
        <span>{values.length} of {maxItems} selected</span>
        {required && values.length === 0 && (
          <span className="text-red-500">At least one selection required</span>
        )}
      </p>
    </div>
  );
}
