// frontend/src/components/ui/multiselect.tsx
import React, { useState, useRef, useEffect } from 'react';
import { X, Plus, Loader2 } from 'lucide-react';
import { useDebounce } from '../../hooks/useDebounce';

interface MultiSelectProps {
  label: string;
  icon: React.ReactNode;
  values: string[];
  onChange: (values: string[]) => void;
  fetchOptions: (search: string) => Promise<string[]>;
  maxItems?: number;
  required?: boolean;
  placeholder?: string;
  debounceMs?: number;
  loading?: boolean
}

export function MultiSelect({
  label,
  icon,
  values,
  onChange,
  fetchOptions,
  maxItems = 5,
  required = false,
  placeholder = 'Select...',
  debounceMs = 300,
  loading = false
}: MultiSelectProps) {
  const [search, setSearch] = useState('');
  const [showOptions, setShowOptions] = useState(false);
  const [isLoading, setIsLoading] = useState(loading);
  const [options, setOptions] = useState<string[]>([]);
  const wrapperRef = useRef<HTMLDivElement>(null);

  // Create debounced fetch function
  const handleSearch = async (searchTerm: string) => {
    try {
      setIsLoading(true);
      const fetchedOptions = await fetchOptions(searchTerm);
      setOptions(fetchedOptions.filter(option => !values.includes(option)));
    } catch (error) {
      console.error('Error fetching options:', error);
      setOptions([]);
    } finally {
      setIsLoading(false);
    }
  };

  const debouncedSearch = useDebounce(handleSearch, debounceMs);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (wrapperRef.current && !wrapperRef.current.contains(event.target as Node)) {
        setShowOptions(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Fetch options when search changes
  useEffect(() => {
    if (search.trim()) {
      debouncedSearch(search);
    } else {
      setOptions([]);
    }
  }, [search, debouncedSearch]);

  const handleAdd = (option: string) => {
    if (values.length < maxItems) {
      onChange([...values, option]);
      setSearch('');
      setShowOptions(false);
      setOptions([]);
    }
  };

  const handleRemove = (option: string) => {
    onChange(values.filter(v => v !== option));
  };

  const canAddMore = values.length < maxItems;

  return (
    <div ref={wrapperRef} className="space-y-2">
      <label className="block text-sm font-medium text-gray-700">
        <div className="flex items-center gap-2">
          {icon}
          {label}
          {required && <span className="text-red-500">*</span>}
        </div>
      </label>

      {/* Selected Items */}
      <div className="flex flex-wrap gap-2 mb-2">
        {values.map((value) => (
          <span
            key={value}
            className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full bg-blue-100 text-blue-800 text-sm"
          >
            {value}
            <button
              type="button"
              onClick={() => handleRemove(value)}
              className="p-0.5 hover:bg-blue-200 rounded-full transition-colors duration-150"
            >
              <X className="w-3 h-3" />
            </button>
          </span>
        ))}
      </div>

      {/* Input Field */}
      {canAddMore && (
        <div className="relative">
          <div className="relative">
            <input
              type="text"
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                setShowOptions(true);
              }}
              onFocus={() => setShowOptions(true)}
              className="w-full px-4 py-2.5 rounded-lg border border-gray-300 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors duration-200"
              placeholder={placeholder}
            />
            {isLoading ? (
              <Loader2 className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 animate-spin" size={20} />
            ) : (
              <Plus className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
            )}
          </div>

          {/* Dropdown */}
          {showOptions && (search.trim() || options.length > 0) && (
            <div className="absolute z-10 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg max-h-60 overflow-y-auto">
              {isLoading && search.trim() ? (
                <div className="px-4 py-2 text-gray-500">Loading...</div>
              ) : options.length > 0 ? (
                options.map((option) => (
                  <button
                    key={option}
                    type="button"
                    className="w-full px-4 py-2 text-left hover:bg-blue-50 transition-colors duration-150"
                    onClick={() => handleAdd(option)}
                  >
                    {option}
                  </button>
                ))
              ) : search.trim() ? (
                <div className="px-4 py-2 text-gray-500">No results found</div>
              ) : null}
            </div>
          )}
        </div>
      )}

      {/* Helper Text */}
      <p className="text-sm text-gray-500 flex items-center justify-between">
        <span>{values.length} of {maxItems} selected</span>
        {required && values.length === 0 && (
          <span className="text-red-500">At least one selection required</span>
        )}
      </p>
    </div>
  );
}

// frontend/src/lib/components/MultiSelect.svelte
<script>
	import { onMount, onDestroy } from 'svelte';
	import { X } from 'lucide-svelte';
	import axios from 'axios';

	const {
		apiEndpoint = '/api/options/countries',
		queryDep = $bindable(''),
		onChange = (values) => {},
		label = '',
		values = [],
		max = 5,
		icon = null,
		debounceMs = 300,
		...props
	} = $props();

	let isOpen = $state(false);
	let isOptionClickPending = $state(false);
	let selectedValues = $state(values);
	let inputValue = $state('');
	let options = $state([]);
	let filteredOptions = $derived(options.filter((value) => !selectedValues.includes(value)));
	let loading = $state(false);
	let debounceTimeout;

	const api = axios.create({
		baseURL: apiEndpoint,
		timeout: 5000
	});

	async function fetchOptions(query) {
		if (!query.trim()) {
			options = [];
			return;
		}

		try {
			loading = true;
			const params = { q: query, c: queryDep };
			const { data } = await api.get('', { params });

			options = Array.isArray(data)
				? data.filter((option) => !selectedValues.includes(option))
				: [];
		} catch (error) {
			console.error('Error fetching options: ', error);
			error = 'Error fetching options: ' + error;
			options = [];
		} finally {
			loading = false;
		}
	}

	function handleInputChange(e) {
		inputValue = e.target.value;
		isOpen = true;

		clearTimeout(debounceTimeout);
		debounceTimeout = setTimeout(() => {
			fetchOptions(inputValue);
		}, debounceMs);
	}

	function handleOptionClick(option) {
		selectedValues.push(option);
		onChange(selectedValues);
	}

	function handleOptionKeyDown(e, option) {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			handleOptionClick(option);
		}
	}

	function handleRemoveValue(valueToRemove) {
		selectedValues = selectedValues.filter((value) => value !== valueToRemove);
		onChange(selectedValues);
	}

	onDestroy(() => {
		clearTimeout(debounceTimeout);
	});
</script>

<div class="relative w-full">
	<span class="mb-1 block flex gap-2 font-medium font-semibold text-gray-700">
		{#if icon}
			<div class="pl-2 text-blue-600">
				{@render icon('')}
			</div>
		{/if}
		{label}
	</span>
	<div class="py-1">
		{#each selectedValues as value}
			<div class="flex inline-flex px-1 py-1">
				<span
					class="inline-flex items-center rounded-md border-transparent bg-blue-100 px-2 py-1 text-sm text-blue-800"
				>
					{value}
					<button
						type="button"
						onclick={() => handleRemoveValue(value)}
						class="ml-1 text-blue-600 hover:text-blue-800"
						aria-label={`Remove ${value}`}
					>
						<X />
					</button>
				</span>
			</div>
		{/each}
	</div>

	{#if values.length < 5}
		<div
			class="min-h-[42px] rounded-md border border-gray-300 p-1 focus-within:border-transparent focus-within:ring-2 focus-within:ring-blue-500"
		>
			<div class="flex flex-wrap gap-1">
				<input
					type="text"
					bind:value={inputValue}
					oninput={handleInputChange}
					onfocusin={() => (isOpen = true)}
					onfocusout={() => (isOpen = false)}
					class="min-w-[120px] flex-1 border-transparent p-1 outline-none"
					placeholder="Type to search..."
					aria-expanded={isOpen}
					aria-controls="multiselect-options"
					role="combobox"
					{...props}
				/>
			</div>
		</div>
		{#if isOpen || isOptionClickPending}
			<div
				id="multiselect-options"
				class="absolute z-10 mt-1 w-full rounded-md border border-transparent bg-white shadow-lg"
				role="listbox"
			>
				{#if loading}
					<div class="flex justify-center p-2">
						<div
							class="h-5 w-5 animate-spin rounded-full border-2 border-blue-500 border-t-transparent"
						></div>
					</div>
				{:else if filteredOptions.length > 0}
					{#each filteredOptions as option}
						<button
							type="button"
							onclick={() => handleOptionClick(option)}
							onkeydown={(e) => handleOptionKeyDown(e, option)}
							onmouseenter={() => {
								isOptionClickPending = true;
							}}
							onmouseleave={() => {
								isOptionClickPending = false;
							}}
							class="w-full cursor-pointer px-4 py-2 text-left hover:bg-gray-100"
							role="option"
							aria-selected="false"
						>
							{option}
						</button>
					{/each}
				{/if}
			</div>
		{/if}
	{/if}
</div>
